config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  get 'sessions/index'
  # get 'customers/index'
  # get 'movies/index'
  # get 'movies/show/:id', to: "movies#show"
  get 'screens/index'
  # get 'theatres/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'theatres/movies/index'
  # Defines the root path route ("/")
  # root "articles#index"

  resources :movies
  resources :customers

  # resources :users
  # resources :sessions

  # get 'sessions/new'
  # post 'sessions/create'

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  # get 'users/new'
  # post 'users/create'
  # delete 'users/destroy'

  root "theatres#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
	belongs_to :theatre, optional:true
	belongs_to :movie, optional:true

#---------------------------- new work ------------------------------ 
	before_save :downcase_email
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness:true ,format: { with: VALID_EMAIL_REGEX }


	PASSWORD_REGEX = /\A (?=.{6,})(?=.*\d)(?=.*[a-z])/x
  	has_secure_password
  	validates :password, length: { minimum: 6 }, allow_blank: true , :format => {:with => PASSWORD_REGEX, message: "at least 6 characters and must include one number and one letter."},unless: Proc.new { |a| a.password.blank? }

	def downcase_email
		self.email = email.downcase
	end

end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :theatre
end

app/models/movie.rb
class Movie < ApplicationRecord
	belongs_to :screen
	has_many :customers
	
	validates :name, presence:true, uniqueness:true
end

app/models/screen.rb
class Screen < ApplicationRecord
	has_one :movie
	has_many :customers, through: :movie
	belongs_to :theatre

	
	validates :screen_id, presence: true, uniqueness: true, numericality: true

# ----------------------------------Not for use--------------------------------
	# using scope
	# scope :created_before ,-> {where("created_at < ?", Date.today)}

	# def self.created_before
	# 	where("created_at < ?", Date.today)
	# end
# -----------------------------------------------------------------------------

end

app/models/theatre.rb
class Theatre < ApplicationRecord
	has_many :customers
	has_many :employees
	has_many :screens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include SessionsHelper
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    # ----------------------------------------------------------------
    # ------- used when we have to get all users of that movie--------
    # binding.pry
    # if params[:movie_id].present?
    #   @customers = Customer.where(movie_id:params[:movie_id])
    # else
    #   @customers =Customer.all
    # end
    # ----------------------------------------------------------------
  end

  def show
    # @customer =Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      sign_in @customer
      flash[:success] = "Welcome, you have successfully created your account !"
      redirect_to screens_index_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @customer = Customer.find(params[:customer_id])
    @movie = Movie.find(params[:movie_id])
    @theatre = Theatre.find(params[:theatre_id])

  end

  def update
    @customer = Customer.find(params[:customer_id])
    if @customer.update(book_ticket)
      redirect_to sessions_index_path
    end
  end


    # ----------------------------------------------------

    # @movie = Movie.find_by(id: params[:movie_id])
    
    # @customer = @movie.customers.build(customer_params)
    # @customer.save
    # redirect_to users_path
    # render plain: "Ticket Booked"

    #  ---------------------------------------------------



  private

  #-------- to book the ticket --------

    def book_ticket
      params.permit(:theatre_id,:movie_id)
    end

  # ------- to create a new customer/sign_up --------

    def customer_params
      params.require(:customer).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    # ----------- not for use ------------
    # # @movies =Movie.all
    # @movie = Movie.released_before
  end

  def show
    @movie= Movie.find(params[:id])
  end

  def new
    @movie =Movie.new
  end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  def index
    @screens = Screen.all
  end

  def show
    @screen = Screen.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    entered_email = params[:session][:email].downcase
    
    # checking whether the email is nil or not
    if entered_email != ""
      customer = Customer.find_by(email: params[:session][:email].downcase)

      # if customer is present in the database
      if customer 
        # checking whether the details of customer entered are authentic or not
        if customer && customer.authenticate(params[:session][:password])
          sign_in customer
          flash[:success] = "Welcome, you are signed in ..."
          redirect_to screens_index_path

        # else
        #   flash[:error] = "Password does not match"
        #   redirect_to sessions_new_path
        end

      else
        flash[:error]='Email does not exist'
        redirect_to sessions_new_path
      end

    else
      flash[:error]='Fields can not be blank'
      redirect_to sessions_new_path
    end
  end

  def destroy
    sign_out if signed_in?
    redirect_to root_path
    flash[:info] = "Signed Out !"
  end

end

# ----------------------------------------------------------------

# -----------------------------------------------------------------
        # @customers =Customer.all
        # entered_email = params[:session][:email].downcase    
        #elsif customer == nil
        #flash[:error]="Email field can't be blank"
        #redirect_to sessions_new_path    

        # elsif !customer.present?  
        #   flash[:error]='Email does not exist.'
        #redirect_to sessions_new_path   

# -----------------------------------------------------------------

# ------------------------ previous work --------------------------


  #   user = User.find_by(email: params[:session][:email])
  #   # user.present?
  #   if user && user.authenticate(params[:session][:password])
  #     # session[:user_id] = user.id
  #     sign_in user
  #     redirect_to screens_index_path
  
  #   else
  #     # flash[:danger]='Invalid credentials'
  #     render 'new'
  #   end
  # end




  # def current_user
  #   @current_user = @current_user || User.find_by(id: session[:user_id])
  # end

  # def signed_in?
  #   !current_user.nil?
  # end


  # def sign_in(user)
  #   session[:user_id] = user.id
  # end
# ---------------------------------------------------------------

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  def index
    @theatre = Theatre.all
  end

  def show
    @theatre = Theatre.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper	

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(customer)
		session[:customer_id] = customer.id
	end
	
	def current_customer
		@current_customer = @current_customer || Customer.find_by(id: session[:customer_id])
	end

	def signed_in?
		!current_customer.nil?
	end

	def sign_out
		session.delete(:customer_id)
		@current_customer = nil
	end
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/bookings/create.html.erb
<h1>Bookngs#create</h1>
<p>Find me in app/views/bookngs/create.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookngs index</h1>

app/views/bookings/new.html.erb
<%= form_with model: @bookng, url: bookngs_path(screen_id: @screen.id, movie_id: @movie.id, show_id: @show.id, bookng_id: @bookng.id), method: :post, local: true do |f| %>
  <div class="form-group">
    <label>How many seat you want to book </label> 
    <%= f.number_field :number_of_seats, in: 1..10, step: 1 %>
    </br>
  </div>
  <% @screen.seats.each do |seat|%>
    <div>
      <%= f.check_box :seat_ids, { multiple: true }, seat.id, nil %>
      <b> Seat No: </b> <%= seat.seat_no %>
    </div>
  <% end %>

  <div class="bookng-info">
    <%= f.hidden_field :screen_id, :value => @screen.id %>
    <%= f.hidden_field :cinema_id, :value => @screen.cinema.id %>
    <%= f.hidden_field :show_id, :value => @show.id %>
    <%= f.hidden_field :status, :value => "initiated" %>
 </div>
  <%= f.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Bookngs Details</h1>
<h3> <b> Bookng status :  </b> <%= @bookng.status %> </h3>
<h4> <b> movie name </b> <%= @bookng.show.movie.name %> </h4>
<p> <b> Show date </b> <%= @bookng.show.date %> </p>
<p> <b> Seat No. you have choosed are :- </b> <%= @bookng.seat_ids %> </p>
<p> <b> Show time </b> <%= @bookng.show.start_time %> </p>
<p> <b> Number of Seats you want to book </b> <%= @bookng.number_of_seats%> </p>
<h6> Total ammount <%= (@bookng.number_of_seats) * 150 %> </h6>

<%= link_to "Pay", new_payment_path(bookng_id: @bookng.id) %>

app/views/home/index.html.erb
<div class="card mx-auto text-center " style="width: 50%;">
  <div class="card-header text-white bg-success">
    <h3> Welcome To our Ticket Booking Website </h3>
    
  </div>
  <div class="card">
    <h4> This is our Home Page </h4>
  </div>
  <div class="card-footer text-muted text-white bg-info">
    <h4> To see Latest Movies Click here  <a href="/movies">Movies Lists</a> </h4>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookTicket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'style.css' %>
   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

  </head>

  <body>

  <%= render 'layouts/navbar' %>


  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
    <%= yield %>

    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Movies Lists</h1>
<ul>
<% @movies.each do |movie| %>
  <li>
    <h2> <b> Movie Name : </b> <%= link_to "#{movie.name.capitalize}", movie_path(movie.id) %> </h2> 
    <p> <b> Movie desc : </b> <%=movie.desc%> </p>
    <p> <b> release date : </b> <%=movie.release_date%> </p>
    <p> <b> Duration : </b> <%=movie.duration%> </p>
    <p> <b> Genere : </b> <%=movie.genere%> </p>
    <p> <b> Language : </b> <%=movie.language%> </p>
  </li>

  <% end %>
</ul>

app/views/movies/screen.html.erb
<h1>Screens Lists</h1>

app/views/movies/show.html.erb
<h1>All the Show available for <%= @movie.name %> moive  </h1>

<div class="card" >
  <div class="card-body">
    <h5 class="card-title"><b> Movie Name : </b> <%= @movie.name %> </h5>
    <p class="card-text"> <b> Movie desc : </b> <%= @movie.desc %>  </p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"> <b> release date : </b> <%= @movie.release_date %> </li>
    <li class="list-group-item"> <b> Duration : </b> <%= @movie.duration %> </li>
    <li class="list-group-item"> <b> Genere : </b> <%= @movie.genere %> </li>
    <li class="list-group-item"> <b> Language : </b> <%= @movie.language %> </li>

    </ul>
</div>

<h3 class="p-3 mb-2 bg-primary text-white text-center"> Show list of <%= @movie.name %> are below </h3> 

  <% @movie.shows.each do |show| %>
    <div class="col- mb-4">
      <div class="card text-center ">
        <div class="card-header"> 
          <h3 class="p-3 mb-2 bg-secondary text-white "> Cinema Name :  <%=show.screen.cinema.name%> </h3>
        </div>
        <div class="card-body">
          <h5 class="card-title"> Date : <%=show.date%> </h5>
          <p class="card-text"> <b> Movie name : </b> <%=show.movie.name%>  </p>
          <p class="card-text"> <b> Show start at  : </b> <%=show.start_time%> </p>
          <p class="card-text"> <b> Show end at : </b> <%=show.end_time%> </p>
          <p> Book Your Ticket here -> <%= link_to "#{show.screen.name.capitalize}", screen_path(id: show.screen.id, movie_id: @movie.id, show_id: show.id) %> </p>
        </div>
        <div class="card-footer text-muted">
          <h3 class=" text-warning"> Hurry up only few seats are left </h3> 
        </div>
      </div>
    </div>
<% end %> 

app/views/payments/create.html.erb
<div class="card mx-auto text-center " style="width: 50%;">
  <div class="card-header text-white bg-success">
    <h2>Great! Your payment of <%= (@bookng.number_of_seats) * 150 %> was successful!</h2>
  </div>
  <div class="card-footer text-muted text-white bg-info">
    <h6> Total ammount you paid : <%= (@bookng.number_of_seats) * 150 %> </h6>
  </div>
</div>


<%= form_with model: @ticket, url: tickets_path(bookng_id: @bookng.id), method: :post, local: true do |f| %>

  <div class="bookng-info">
    <%= f.hidden_field :screen_id, :value => @bookng.show.screen.id %>
    <%= f.hidden_field :show_id, :value => @bookng.show.id %>
    <%= f.hidden_field :bookng_id, :value => @bookng.id %>
    <%= f.hidden_field :total_price, :value => (@bookng.number_of_seats) * 150 %>
 </div>
  <%= f.submit 'To see your Ticket Click here ', class: "btn btn-default btn-primary" %>


<% end %>

app/views/payments/index.html.erb
<h1>payment index </h1>

app/views/payments/new.html.erb
<h1>Bookngs Details</h1>
<h3> <b> Bookng status :  </b> <%= @bookng.status %> </h3>
<h4> <b> movie name </b> <%= @bookng.show.movie.name %> </h4>
<p> <b> Show date </b> <%= @bookng.show.date %> </p>
<p> <b> Seat No. you have choosed are :- </b> <%= @bookng.seat_ids %> </p>
<p> <b> Show time </b> <%= @bookng.show.start_time %> </p>
<p> <b> Number of Seats you want to book </b> <%= @bookng.number_of_seats%> </p>
<h6> Total ammount <%= (@bookng.number_of_seats) * 150 %> </h6>

<%= form_tag payments_path(bookng_id: @bookng.id) do %>
  <label class="amount">
      <span>Amount: $<%= (@bookng.number_of_seats) * 150 %></span>
      <input type=”hidden” name=”stripeToken” />

  </label>

  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Book Ticket"
    data-amount="(<%= (@bookng.number_of_seats) * 150 %>)*100"
    data-locale="auto">
  </script>
<% end %>

<script src=”https://js.stripe.com/v2/”></script> 
<script>

  Stripe.setPublishableKey("pk_test_51NreVhSEjAF4aUMyfvuULqhvomE9EHq5q9gZNXKnO1HnLQzjTTHyZEksFOnlFRKgTiBXNMDZ5BjcO6xVaeGGVuyP00jfVmafIk");

</script>

app/views/payments/show.html.erb
<h1> payment show </h1> 

app/views/screens/index.html.erb
<h1>Screens Lists</h1>

app/views/screens/show.html.erb
<h1>Screen Details</h1>
<h3> <%= @screen.name %> </h3>
<h4> <b> Cinema Name :- </b> <%= @screen.cinema.name %> </h4>
<p> <b> Seat Price :- </b> 150 RS </p>
<div class="screen-container"> 
  <h4> Screen is here </h4>
</div>

  <div class="container">
    <% @screen.seats.each do |seat|%>
      <div class="item">  <p style="display:inline-block;" > <b>Type : </b> <%=seat.seat_type%> <b> Row : </b> <%=seat.seat_row%> <b> Seat No: </b> <%=seat.seat_no%> </p> </div>
    <% end %> 
  </div>
  <%= link_to "Book Seat", new_bookng_path(screen_id: @screen.id, movie_id: @movie.id, show_id: @show.id) %>

app/views/tickets/create.html.erb
<h1> ticket create </h1>

app/views/tickets/index.html.erb
<h1> ticket index </h1>

app/views/tickets/new.html.erb
<%= form_with model: @ticket, url: tickets_path(bookng_id: @bookng.id, ticket_id: @ticket.id), method: :post, local: true do |f| %>

  <div class="bookng-info">
    <%= f.hidden_field :screen_id, :value => @bookng.show.screen.id %>
    <%= f.hidden_field :show_id, :value => @bookng.show.id %>
    <%= f.hidden_field :bookng_id, :value => @bookng.id %>
    <%= f.hidden_field :total_price, :value => (@bookng.number_of_seats) * 150 %>
 </div>
  <%= f.button :submit => "click here to see your ticket", class: "btn btn-primary" %>

<% end %>

app/views/tickets/show.html.erb
<div class="card mx-auto text-center " style="width: 50%;">
  <div class="card-header text-white bg-success">
    <h2>Your Ticket is here </h2>
  </div>
  <div class="card-body">
    <h5 class="card-title"> <b> movie name </b> <%= @bookng.show.movie.name %> </h5>
    <p class="card-text"> <b> Show date </b> <%= @bookng.show.date %> </p>
    <p class="card-text"> <b> Show time </b> <%= @bookng.show.start_time %> </p>
    <p class="card-text"> <b> Seat No. you have choosed are :- </b> <%= @bookng.seat_ids %> </p>
    <p class="card-text"> <b> Number of Seats you have booked are </b> <%= @bookng.number_of_seats%> </p>
  </div>
  <div class="card-footer text-muted text-white bg-info">
    <h6> Total ammount you paid : <%= (@bookng.number_of_seats) * 150 %> </h6>
  </div>
</div>